config/routes.rb
Rails.application.routes.draw do
  get '/login'  => 'application#login', as: :login
  post '/login' => 'application#login'
  get '/logout' => 'application#logout', as: :logout
  get '/ping'   => 'application#ping'

  github_authenticated do
    get '/settings/htee.conf' => 'application#config_file', as: :config
    get '/settings'           => 'application#settings', as: :settings

    delete '/:owner/:name' => 'application#delete'

    get '/' => 'application#dash', as: :dash
  end

  post '/(:owner/:name)' => 'application#record'
  put  '/(:owner/:name)' => 'application#record'
  get  '/:owner/:name'   => 'application#playback', as: :stream

  get '/' => 'application#splash', as: :splash

  root to: 'application#splash'

  match '*all' => 'application#not_found', via: :all
end

app/models/stream.rb
class Stream < ActiveRecord::Base
  after_initialize :init

  belongs_to :user

  enum status: {
    :created => 0,
    :opened  => 1,
    :closed  => 2,
    :gisted  => 3,
  }

  def init
    self.name ||= SecureRandom.hex(10)
    self.name = self.name.parameterize
  end

  def owner
    user.login
  end

  def nwo
    "#{owner}/#{name}"
  end

  def path
    "/#{nwo}"
  end

  def gist(octokit, url)
    response = Rack::Client.get(url)

    if response.status == 200
      gist = octokit.create_gist \
        public: false,
        files: {
          "htee:#{name}.sh-session" => {
            content: response.body,
          },
        }

      update(gist_id: gist[:id], status: :gisted)
    end
  end

  def gist_path
    "/#{owner}/#{gist_id}"
  end
end

app/models/token.rb
class Token < ActiveRecord::Base
  after_initialize :init

  belongs_to :user

  def init
    self.key ||= SecureRandom.hex
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :streams
  has_many :tokens

  after_create :generate_token

  def self.anon
    find_by_login('anonymous')
  end

  def generate_token
    tokens.create if tokens.empty?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception, except: :record

  before_action :authenticate, only: :record
  before_action :find_user,    only: [:dash, :settings, :config_file, :delete]

  def login
    github_authenticate!

    user = User.find_or_create_by(login: github_user.login)

    if user.email != github_user.email || user.name != github_user.name
      user.update(email: github_user.email, name: github_user.name)
    end

    redirect_to root_url
  end

  def logout
    github_logout

    redirect_to root_url
  end

  def record
    if request.xhr?
      stream = @user.streams.create(status: :created)
      return render_new_stream(stream)
    elsif stream = @user.streams.find_by_name(params[:name])
      stream.update(status: :opened)
    else
      stream = @user.streams.create(status: :opened)
    end

    downstream_rewrite(path: stream.path, method: 'POST')
  end

  def playback
    @owner  = User.find_by(login: params[:owner])
    return render nothing: true, status: 404 if @owner.nil?

    @stream = @owner.streams.find_by_name(params[:name])
    return render nothing: true, status: 404 if @stream.nil?

    if request.xhr?
      return render nothing: true, status: 201 if @stream.created?

      return render partial: 'stream.html', locals: {stream: @stream, stream_class: "stream-full"}
    end

    if @stream.gisted?
      return redirect_to "https://gist.github.com#{@stream.gist_path}/raw", status: 301
    end

    return render :sse if sse_supported_browser? unless event_stream_request?

    downstream_rewrite(path: @stream.path)
  end

  def dash
    @streams = @user.streams.
      where.not(status: Stream.statuses[:created]).
      paginate(:page => params[:page], :per_page => 10).
      order(created_at: :desc)
  end

  def delete
    owner = User.find_by(login: params[:owner])
    return render nothing: true, status: 401 unless @user == owner

    stream = owner.streams.find_by_name(params[:name])
    return render nothing: true, status: 404 if stream.nil?

    if params[:commit] == 'gist'
      stream.gist(github_user.api, request.url)
    else
      stream.destroy
    end

    set_downstream_continue

    if request.referer == stream_url(stream.owner, stream.name)
      redirect_to dash_path
    else
      redirect_to :back
    end
  end

  def ping
    render text: "PONG!"
  end

  def config_file
    render partial: 'config.toml', content_type: 'application/octet-stream'
  end

  def downstream_rewrite(request = {})
    render status: 202, json: request_hash.merge(request)
  end

  def sse_supported_browser?
    request.env['HTTP_USER_AGENT'] =~ /WebKit|Gecko|Presto/
  end

  def event_stream_request?
    request.env['HTTP_ACCEPT'] == 'text/event-stream'
  end

  def authenticate
    github_authenticate || anon_authenticate || token_authenticate || render_unauthorized
  end

  def token_authenticate
    authenticate_or_request_with_http_token do |token, options|
      @user = User.includes(:tokens).where("tokens.key" => token).first
    end
  end

  def anon_authenticate
    auth_header = request.headers['HTTP_AUTHORIZATION']

    if auth_header.blank? || auth_header =~ /Basic/
      @user = User.anon
    end
  end

  def github_authenticate
    @user = User.find_by(login: github_user.login) if github_authenticated?
  end

  def render_unauthorized
    self.headers['WWW-Authenticate'] = 'Token realm="Application"'
    render nothing: true, status: 401
  end

  def render_errors(*errors)
    render status: 400, json: {
      errors: errors
    }
  end

  def render_new_stream(stream)
    render status: 200, json: {
      owner: stream.owner,
      name: stream.name,
      status: stream.status,
      url: stream_url(stream.owner, stream.name)
    }
  end

  def find_user
    @user = User.find_by(login: github_user.login)

    redirect_to logout_path if @user.nil?
  end

  def request_hash
    {
      method:  request.method,
      path:    request.fullpath,
    }
  end

  def set_downstream_continue
    response.headers['X-Htee-Downstream-Continue'] = 'yes'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_config.toml.erb
token = "<%= @user.tokens.first.key %>"
login = "<%= @user.login %>"
endpoint = "<%= root_url %>"

app/views/application/_lite_stream_modal.html.erb
<div class="modal modal-wide fade" id="lite-stream-modal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="myModalLabel">Lite Stream</h4>
      </div>
      <div class="modal-body">
        <p>Pipe your stream to this curl command:</p>
        <pre></pre>
      </div>
    </div>
  </div>
</div>

app/views/application/_new_stream_modal.html.erb
<div class="modal modal-wide fade" id="new-stream-modal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="myModalLabel">New Stream</h4>
      </div>
      <div class="modal-body">
        <p>Pipe your stream to this curl command:</p>
        <pre></pre>
      </div>
    </div>
  </div>
</div>

app/views/application/_show_stream_modal.html.erb
<div class="modal modal-wide fade" id="show-stream-modal">
  <div class="modal-dialog">
    <div class="modal-content"><div/>
    </div>
  </div>
</div>

app/views/application/_stream.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <%= form_tag(stream_path(stream.owner, stream.name), method: :delete, class: "delete pull-right #{'invisible' if stream.opened?}") do %>
      <%= submit_tag('Delete', value: 'delete', class: "btn btn-xs btn-danger") %>
      <%- unless stream.gisted? %>
        <%= submit_tag('Gist', value: 'gist', class: "btn btn-xs btn-warning") %>
      <%- end %>
    <% end %>
    <h3 class="panel-title">
      <span class="status htee-font <%= stream.opened? ? 'recording' : 'finished' %>">ht</span>
      <%= link_to stream.nwo, stream_path(stream.owner, stream.name) %>
    </h3>
  </div>
  <div class="panel-body">
  <%- if stream.gisted? %>
    <script src="https://gist.github.com<%= stream.gist_path %>.js"></script>
  <%- else %>
    <pre class="stream <%= stream_class %>" href="<%= stream_url(stream.owner, stream.name) %>"></pre>
  <%- end %>
  </div>
</div>

app/views/application/dash.html.erb
<div class="container">
  <div class="row">

  <%- @streams.each do |stream| -%>
    <%= render partial: "stream", locals: {stream: stream, stream_class: "stream-preview"} %>
  <%- end %>

  <%= will_paginate @streams, renderer: BootstrapPagination::Rails %>
  </div>
</div>

app/views/application/settings.html.erb
<div class="container">
  <div class="row">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">API Tokens</h3>
      </div>
      <ul class="list-group">
      <%- @user.tokens.each do |token| -%>
        <li class="list-group-item"><%= token.key %></li>
      <%- end -%>
      </ul>
    </div>
    <div class="panel panel-default">
      <div class="panel-heading">
        <h4 class="panel-title">Config File</h4>
      </div>
      <div class="panel-body">
        <pre><%= link_to 'Download', config_path, class: 'btn btn-xs btn-info pull-right' %><code><%= render 'config.toml', locals: {user: @user} %></code></pre>
        Save this as your <strong>~/.htee.conf</strong> file.
      </div>
    </div>
  </div>
</div>

app/views/application/splash.html.erb
 <div class="jumbotron">
  <div class="container">
    <h1>This is a splash page!</h1>
    <p>There are many like it but this one is mine.</p>
    <p><a class="btn btn-primary btn-lg" role="button">Try htee &raquo;</a></p>
  </div>
</div>

app/views/application/sse.html.erb
<div class="container">
  <div class="row">
    <%= render partial: "stream", locals: {stream: @stream, stream_class: "stream-full"} %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>htee</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'favicon.ico' %>
</head>
<body>
  <div class="container">
    <div class="row">
      <div class="navbar navbar-inverse" role="navigation">
        <div class="navbar-header">
          <%= link_to 'htee', root_path, class: 'htee-font navbar-brand' %>
        </div>
        <div class="navbar-collapse">
          <ul class="nav navbar-nav">
            <li>
              <a class="btn navbar-btn btn-default" data-toggle="modal" data-target="#new-stream-modal">
                New Stream
              </a>
            </li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
          <%- if github_user -%>
            <li class="dropdown">
              <button class="btn navbar-btn btn-default dropdown-toggle" data-toggle="dropdown">
                <%= gravatar_image_tag(github_user.email, class: 'gravatar-img') %>
                <%= github_user.name %>
                <span class="caret"></span>
              </button>
              <ul class="dropdown-menu">
                <li>
                  <%=link_to 'Settings', settings_path %>
                </li>
                <li class="divider"></li>
                <li>
                  <%=link_to 'Sign out', logout_path %>
                </li>
              </ul>
            </li>
          <%- else -%>
            <li>
              <%= button_to 'Sign in with GitHub', login_path, class: 'btn btn-success navbar-btn' %>
            </li>
          <%- end -%>
          </ul>
        </div>
      </div>
    </div>
  </div>

<%= yield %>

<%= render partial: "new_stream_modal" %>
<%= render partial: "show_stream_modal" %>

</body>
</html>